In [3]:
import pandas as pd
import numpy as np

Series.index Defines the index of the Series.

In [ ]:
a=pd.Series(data=[12,34,56,67,78])    
b=pd.Series(data=[10.5,20.5,30.5], index=['a','b','c'])    
print(a.index)    
print(a.values)    `    `
print(b.index)    
print(b.values)

RangeIndex(start=0, stop=5, step=1)
[12 34 56 67 78]
Index(['a', 'b', 'c'], dtype='object')
[10.5 20.5 30.5]

In [5]:
a=pd.Series(data=[12,34,56,67,78])    
b=pd.Series(data=[10.5,20.5,30.5], index=['a','b','c'])    
print(a.dtype)
print(b.dtype)

int64
float64

Series.shape It returns a tuple of shape of the data.

In [6]:
dt=np.array([1,2,3,4]) 
sr=pd.Series(dt,index=['alpha','beta','gama','delta']) 
print(sr) 
print(sr.shape)

alpha    1
beta     2
gama     3
delta    4
dtype: int64
(4,)

Series.dtype It returns the data type of the data.

Series.empty It returns True if Series object is empty, otherwise returns false.

Series.hasnans It returns True if there are any NaN values, otherwise returns false.

Series.nbytes It returns the number of bytes in the data.

Series.ndim It returns the number of dimensions in the data.

In [ ]:
dt=np.array([1,2,3,4,np.nan]) 
sr=pd.Series(dt,index=['alpha','beta','gama','delta','Epsilon']) 
# print(sr) 
# print(sr.empty) 
# print(sr.hasnans) 
# print(len(sr)) 

print(sr.count)

<bound method Series.count of alpha      1.0
beta       2.0
gama       3.0
delta      4.0
Epsilon    NaN
dtype: float64>

In [8]:
dt=np.array([
    [1,2,3,4,np.nan],
    [5,6,7,8,9]]) 

sr=pd.DataFrame(dt,
            index=['alpha','beta'],
            columns=['a','b','c','d','e']) 
# print(sr)

print(sr.nbytes)  #total bytes consumed by the elements of the Series
print(sr.ndim)

AttributeError: 'DataFrame' object has no attribute 'nbytes'

DataFrame.append()

In [ ]:
import pandas as pd 
a1=pd.DataFrame({'a':[12,13,45,67,89,90],'b':[21,22,89,76,5,34]}) 
b1=pd.DataFrame({'a':[410,420],'b':[310,320],'c':[220,330]}) 
a1.append(b1)

AttributeError: 'DataFrame' object has no attribute 'append'

In [9]:
import pandas as pd 
import numpy as np 
  
df=pd.DataFrame() 
df['subject']=['s1','s2','s3'] 
df.assign(marks=[45,56,76])

  subject  marks
0      s1     45
1      s2     56
2      s3     76

In [10]:
import pandas as pd 
import numpy as np 
df=pd.DataFrame({"sub":['s1','s2','s3'],'marks':[12,13,np.nan]}) 
print(df) 
df.count()

  sub  marks
0  s1   12.0
1  s2   13.0
2  s3    NaN

sub      3
marks    2
dtype: int64

In [11]:
import pandas as pd   
import numpy as np   
a1 = pd.Series([10, 20, 30])   
a1.describe()

count     3.0
mean     20.0
std      10.0
min      10.0
25%      15.0
50%      20.0
75%      25.0
max      30.0
dtype: float64

In [13]:
f = pd.DataFrame({'language':['C', 'C++', 'Python', 'Java','PHP']})   
df.head()   
df.head(3)

  sub  marks
0  s1   12.0
1  s2   13.0
2  s3    NaN

In [14]:
import pandas as pd   
import numpy as np   
 
data = {'Name': ['sachin', 'raj', 'virat', 'dhoni'],   
   'Percentage': [82, 98, 91, 87],   
   'Course': ['B.Sc','B.Ed','M.Phill','BA']}   
df = pd.DataFrame(data)   
   
grouped = df.groupby('Course')   
print(grouped['Percentage'].agg(np.mean))

Course
B.Ed       98.0
B.Sc       82.0
BA         87.0
M.Phill    91.0
Name: Percentage, dtype: float64

C:\Users\korat\AppData\Local\Temp\ipykernel_12972\1703096769.py:10: FutureWarning: The provided callable <function mean at 0x000002A6A44528E0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  print(grouped['Percentage'].agg(np.mean))

In [16]:
import pandas as pd   
import numpy as np   
 
data = {'Name': ['sachin', 'raj', 'virat', 'dhoni'],   
   'Percentage': [82, 98, 91, 87],   
   'Course': ['B.Sc','B.Ed','M.Phill','BA']}   
df = pd.DataFrame(data)   
   
grouped = df.groupby('Course')
print(grouped['Percentage'].agg(np.mean)) 
grouped = df.groupby('Course')   
rs=df.groupby('Course').filter(lambda x:len(x)>=1) 
print(rs)

Course
B.Ed       98.0
B.Sc       82.0
BA         87.0
M.Phill    91.0
Name: Percentage, dtype: float64
     Name  Percentage   Course
0  sachin          82     B.Sc
1     raj          98     B.Ed
2   virat          91  M.Phill
3   dhoni          87       BA

C:\Users\korat\AppData\Local\Temp\ipykernel_12972\922628479.py:10: FutureWarning: The provided callable <function mean at 0x000002A6A44528E0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  print(grouped['Percentage'].agg(np.mean))

In [17]:
import pandas as pd   
import numpy as np 


emp={"name":['a','b','c','a'],"salary":[12000,13000,14000,12000]} 
df=pd.DataFrame(emp) 
print(df) 
df=df.drop_duplicates() 
print(df)

  name  salary
0    a   12000
1    b   13000
2    c   14000
3    a   12000
  name  salary
0    a   12000
1    b   13000
2    c   14000